version: '3.9'

services:
  java_app:
    container_name: java_app
    image: api-java-app:1.0.0
    build: .
    environment:
      - DB_HOST= ${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SEC_SECRET=${SEC_SECRET}