spring:
  profiles:
    active: dev
  application:
    name: Pal Filo Backend
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    dbname: ${DB_NAME}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      dialect: ${JPA_HIBERNATE_DIALECT}
  server:
    port: ${SERVER_PORT}
    servlet:
      context-path: ${SERVER_SERVLET_CONTEXT_PATH}

jwt:
  secret: ${API_SECURITY_SECRET}

maps:
  api:
    key: ${MAP_BOX_API_KEY}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}